### ISSUE TITLE
Feature request: schema names

### ISSUE THREAD

**Issue by richwaring** [rajyraman/Levelup-for-Dynamics-CRM#105]
Browser Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36
    Extension Version: 3.4.6
    ----------------------------------------------------------
Hi there,

first off, thanks very much for your excellent Level Up for D365  /Power Apps - it really does kick arse.

Second - sorry to bother you here with a feature request when this space seems to be for bug reporting but here it is anyway....

As a C# developer extending D365 and Power Platform with the xrm sdk, I need to use (annoying, case sensitive) schema names instead of (sensible, lower case) logical names when referring to fields in my code, and it takes time to pick them out.

I would love the simplicity and quickness of being able to retrieve these via the Level Up for Dynamics CRM e.g...
        - either with a "Schema Names" button and inserted fields on the form like the great one that you have for logical names ... OR...
        - as another column in the "All fields" view.

What do you reckon?

Many thanks,

Rich Waring

**Comment by BetimBeja** [comment]
Hello @richwaring ,
I think it would make sense to add another column to the `All Fields` view for the `Schema Names`.

I am curious when you state that you need to use the schema names when referring to fields in your code, is that because you are using Early Bound entities? Also I think that Visual Studio intellisense does a pretty good job correcting the casing so I don't really understand what is your use case. 

Best regards,
Betim Beja.

**Comment by rajyraman** [comment]
@richwaring - You can now see this in hamburger menu under entity metadata
