### ISSUE TITLE
Build throws lots of errors

### ISSUE THREAD

**Issue by DigitalFlow** [rajyraman/Levelup-for-Dynamics-CRM#72]
Hi @rajyraman,

thanks for your plugin, it's awesome and one of my most used tools.
I would really like to be able to have it available for FireFox as well and tried building your code at my side.

I used the code from your latest commit, ran npm install and npm run-script build. Do you get all these errors as well?
![image](https://user-images.githubusercontent.com/4287938/53951881-bf18eb00-40cf-11e9-9646-a8fd9a744ef7.png)

Kind Regards,
Florian

**Comment by rajyraman** [comment]
Yeah. I get the same too. It is because the tsd's for Xrm client APIs are out of sync and I really haven't fixed them since I started using undocumented methods in Xrm ns and external libraries.

**Comment by piyushpaliwal** [comment]
@rajyraman do you recommend any steps using which we can get the build completed. I was also struggling with the same thing and found this post.

It would be great if you can provide a release for Firefox and Edge and put them up under releases for this project so that people who are really interested can at least use the plug-in.

Thanks for the great work btw.

**Comment by rajyraman** [comment]
@piyushpaliwal - Uploaded the zip file as a release. "npm run chrome" should build and package the extension for chrome, but this currently only only in unsupported version of gulp (3.9.1) and node 10.

**Comment by rajyraman** [comment]
@piyushpaliwal - For Edge Chromium, you can install the extension straight from Chrome Web Store.

**Comment by piyushpaliwal** [comment]
Thanks @rajyraman for uploading the zip, however it fails to load the extension to Firefox. I am guessing you have provided the build for Chrome.

What this issue talks about is having the build for Mozilla Firefox. Since you have the dev environment setup properly, can you please generate a build for this browser and attach the same.

We have tried multiple time unsuccessfully.
